### ISSUE TITLE
An error occurred while installing ivy-yasnippet

### ISSUE THREAD

**Issue by didibus** [mkcms/ivy-yasnippet#3]
When loading spacemace devel 0.300 on Emacs 25.1.1 I getL

"An error occurred while installing ivy-yasnippet (error: (error Package  emacs-25.3  is unavailable))"

Does ivy-yasnipet only works with newer emacs versions?

Thank You

**Comment by mkcms** [comment]
Thanks, I lowered the minimum required version of emacs to 24.


> Does ivy-yasnipet only works with newer emacs versions?
I tested it with emacs 24.5 and it doesn't seem to have any problems.
