### ISSUE TITLE
Assist in porting to consult

### ISSUE THREAD

**Issue by mohkale** [mkcms/ivy-yasnippet#9]
[consult](https://github.com/minad/consult) is a package that tries to bring ivy like completions (with live previews, incremental narrowing and asynchronous commands) to the base `completing-read` interface (which can be used with `ido`, `selectrum`, etc.). I'm currently in the process of porting `ivy-yasnippet` to `consult` (See [consult#173](https://github.com/minad/consult/pull/173)) and I'd like to ask whether you'd be willing to help explain some of the implementation details of `ivy-yasnippet` which I've graciously (copied and pasted) adapted for the `consult--read` interface.

**Comment by conao3** [comment]
This issue is out of topic for this bug tracker, I close it. I move to your issue, please ask me at there if you want some help.
